#!/bin/bash

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
reset='\033[0m'

update() {
  echo -e "${green}Updating repositories...${reset}" &&
  sudo apt-get update
}

apt_install() {
  echo -e "${green}Installing $1...${reset}" &&
  sudo apt-get -y install $1
}

copy_config() {
  echo -e "${green}Copying config $1 to $2...${reset}" &&
  cp ./configs/$1 $2
}

install_curl() {
  apt_install curl
}

install_git() {
  apt_install git &&
  copy_config .gitconfig ~/.gitconfig
}

install_htop() {
  apt_install htop &&
  mkdir -p ~/.config/htop &&
  copy_config htoprc ~/.config/htop/htoprc
}

install_zsh() {
  apt_install zsh &&
  copy_config .zshrc ~/.zshrc &&
  sudo chsh -s /bin/zsh
}

install_vim() {
  apt_install vim &&
  copy_config vim/.vimrc ~/.vimrc &&
  copy_config vim/.selected_editor ~/.selected_editor
}

install_mc() {
  apt_install mc &&
  mkdir -p ~/.config/mc &&
  copy_config mc/ini ~/.config/mc/ini &&
  copy_config mc/panels.ini ~/.config/mc/panels.ini
}

install_fd() {
  apt_install fd-find
}

install_bat() {
  apt_install bat
}

install_ncdu() {
  apt_install ncdu
}

install_gitprompt() {
  echo -e "${green}Installing git-prompt...${reset}" &&
  if [[ -d ~/.git-prompt.zsh ]]; then
    echo -e "${yellow}git-prompt found. Updating...${reset}" &&
    ( cd ~/.git-prompt.zsh && git pull origin master )
  else
    git clone --depth=1 https://github.com/woefe/git-prompt.zsh ~/.git-prompt.zsh
  fi
}

install_rbenv() {
  echo -e "${yellow}Install rbenv? y/n${reset}"
  read should_install_rbenv
  if [[ $should_install_rbenv == 'y' ]]; then
    echo -e "${green}Installing rbenv...${reset}" &&
    copy_config .irbrc ~/.irbrc &&
    if [[ -d ~/.rbenv ]]; then
      echo -e "${yellow}rbenv exists. Updating...${reset}" &&
      ( cd ~/.rbenv && git pull origin master ) &&
      if [[ -d ~/.rbenv/plugins/ruby-build ]]; then
        ( cd ~/.rbenv/plugins/ruby-build && git pull origin master )
      else
        git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      fi
    else
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv &&
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    fi
  elif [[ $should_install_rbenv == 'n' ]]; then
    echo -e "${yellow}Skipping install rbenv.${reset}"
  else
    echo 'Use "y" or "n"'
  fi
}

install_asdf() {
  echo -e "${yellow}Install asdf? y/n${reset}"
  read should_install_asdf
  if [[ $should_install_asdf == 'y' ]]; then
    echo -e "${green}Installing asdf...${reset}" &&
    copy_config .irbrc ~/.irbrc &&
    mkdir -p ~/.local/bin &&
    ( cd ~/.local/bin &&
    wget -qO- --max-redirect=10 $(curl -s 'https://api.github.com/repos/asdf-vm/asdf/releases/latest' | jq -r '.assets[] | select(.name | test("linux-amd64.tar.gz$")) | .browser_download_url') | gunzip -c | tar xv )
  elif [[ $should_install_asdf == 'n' ]]; then
    echo -e "${yellow}Skipping install asdf.${reset}"
  else
    echo 'Use "y" or "n"'
  fi
}

install_zed() {
  echo -e "${green}Installing Zed editor...${reset}" &&
  curl -f https://zed.dev/install.sh | sh
  mkdir -p ~/.config/zed &&
  copy_config zed/settings.json ~/.config/zed/settings.json &&
  copy_config zed/keymap.json ~/.config/zed/keymap.json
}

install_alacritty() {
  apt_install alacritty &&
  copy_config .alacritty.toml ~/.alacritty.toml
}

prepare_firefox_repository() {
  echo -e "${green}Preparing Firefox repository...${reset}" &&
  # Create a directory to store APT repository keys if it doesn't exist
  sudo install -d -m 0755 /etc/apt/keyrings &&
  # Import the Mozilla APT repository signing key
  wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null &&
  # Add the Mozilla APT repository to sources.list
  sudo tee /etc/apt/sources.list.d/mozilla.sources > /dev/null << EOF
Types: deb
URIs: https://packages.mozilla.org/apt
Suites: mozilla
Components: main
Signed-By: /etc/apt/keyrings/packages.mozilla.org.asc
EOF
  # Configure APT to prioritize packages from the Mozilla repository
  sudo tee /etc/apt/preferences.d/mozilla > /dev/null << EOF
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000

Package: firefox
Pin: release o=Ubuntu
Pin-Priority: -1
EOF
}

install_done() {
  echo -e "${green}Workspace has been setup.${reset}"
}

install_for_root() {
  update &&
  install_curl &&
  install_git &&
  install_htop &&
  install_zsh &&
  install_vim &&
  install_mc &&
  install_fd &&
  install_bat &&
  install_ncdu &&
  install_gitprompt &&
  install_rbenv &&
  install_asdf &&
  if [[ x$DISPLAY != x ]]; then
    install_zed &&
    install_alacritty &&
    prepare_firefox_repository &&
    update &&
    install_done
  else
    install_done
  fi
}

install_for_non_root() {
  install_gitprompt &&
  install_rbenv &&
  install_asdf &&
  mkdir -p ~/.config/mc &&
  copy_config mc/ini ~/.config/mc/ini &&
  copy_config mc/panels.ini ~/.config/mc/panels.ini &&
  copy_config vim/.vimrc ~/.vimrc &&
  copy_config vim/.selected_editor ~/.selected_editor &&
  copy_config .irbrc ~/.irbrc &&
  copy_config .zshrc ~/.zshrc &&
  copy_config htoprc ~/.config/htop/htoprc
  install_done &&
  echo -e "${green}. Ask root user to change your default shell to zsh.${reset}"
}

# MAIN SCRIPT

echo 'Sudoer? y/n'
read sudoer
if [[ $sudoer == 'y' ]]; then
  install_for_root
elif [[ $sudoer == 'n' ]]; then
  install_for_non_root
else
  echo 'Use "y" or "n"'
fi
