#!/bin/bash

red='\033[0;31m'
green='\033[0;32m'
reset='\033[0m'

function install_zsh() {
  echo -e "${red}Installing zsh...${reset}" &&
  sudo apt-get -y install zsh &&
  cp ./.zshrc ~/.zshrc &&
  chsh -s /bin/zsh
}

function install_vim() {
  echo -e "${red}Installing vim...${reset}" &&
  sudo apt-get -y install vim &&
  cp ./.vimrc ~/.vimrc &&
  cp ./.selected_editor ~/.selected_editor
}

function install_mc() {
  echo -e "${red}Installing mc...${reset}" &&
  sudo apt-get -y install mc &&
  mkdir -p ~/.config/mc &&
  cp ./ini ~/.config/mc/ini
}

function install_rbenv() {
  echo -e "${red}Installing rbenv...${reset}" &&
  if [[ -d ~/.rbenv ]]; then
    echo -e "${green}rbenv exists. Updating...${reset}" &&
    ( cd ~/.rbenv && git pull origin master ) &&
    if [[ -d ~/.rbenv/plugins/ruby-build ]]; then
      ( cd ~/.rbenv/plugins/ruby-build && git pull origin master )
    else
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
    fi
  else
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv &&
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  fi
}

function install_gitprompt() {
  echo -e "${red}Installing zsh-git-prompt...${reset}" &&
  if [[ -d ~/.zsh-git-prompt ]]; then
    echo -e "${green}zsh-git-prompt found. Updating...${reset}" &&
    ( cd ~/.zsh-git-prompt && git pull origin master )
  else
    git clone https://github.com/olivierverdier/zsh-git-prompt.git ~/.zsh-git-prompt
  fi
}

function install_terminator() {
  echo -e "${red}GUI found. Installing Terminator...${reset}" &&
  sudo apt-get -y install terminator &&
  mkdir -p ~/.config/terminator &&
  cp ./config ~/.config/terminator/config
}

function install_sublime() {
  echo -e "${red}Installing Sublime Text 3 from PPA...${reset}" &&
  sudo apt-get install -y software-properties-common &&
  sudo add-apt-repository ppa:webupd8team/sublime-text-3 &&
  sudo apt-get update &&
  sudo apt-get install -y sublime-text-installer &&
  mkdir -p ~/.config/sublime-text-3/Packages/User &&
  cp ./{Preferences.sublime-settings,JavaScript.sublime-settings,Ruby.sublime-settings,YAML.sublime-settings,CoffeeScript.sublime-settings,Sass.sublime-settings} ~/.config/sublime-text-3/Packages/User/
}

function install_tmux() {
  echo -e "${red}Seems like there is no GUI. Installing tmux...${reset}" &&
  sudo apt-get -y install tmux &&
  cp ./.tmux.conf ~/.tmux.conf
}

function install_done() {
  echo -e "${green}Workspace has been setup."
}

# MAIN SCRIPT

echo 'Sudoer? y/n'
read sudoer

if [[ $sudoer == 'y' ]]; then

  sudo apt-get update &&
  install_zsh &&
  install_vim &&
  install_mc &&
  install_rbenv &&
  install_gitprompt &&
  if [[ x$DISPLAY != x ]]; then
    install_terminator &&
    install_sublime &&
    install_done
  else
    install_tmux &&
    install_done
  fi

elif [[ $sudoer == 'n' ]]; then

  cp ./.zshrc ~/.zshrc &&
  cp ./.vimrc ~/.vimrc &&
  cp ./.selected_editor ~/.selected_editor &&
  mkdir -p ~/.config/mc &&
  cp ./ini ~/.config/mc/ini &&
  install_rbenv &&
  install_gitprompt &&
  if [[ x$DISPLAY != x ]]; then
    mkdir -p ~/.config/terminator &&
    cp ./config ~/.config/terminator/config &&
    mkdir -p ~/.config/sublime-text-3/Packages/User &&
    cp ./{Preferences.sublime-settings,JavaScript.sublime-settings,Ruby.sublime-settings,YAML.sublime-settings,CoffeeScript.sublime-settings,Sass.sublime-settings} ~/.config/sublime-text-3/Packages/User/ &&
    install_done
  else
    cp ./.tmux.conf ~/.tmux.conf &&
    install_done
    echo -e "${green}. Ask root user to change your default shell to zsh."
  fi

else
  echo 'Use "y" or "n"'
fi
