#!/bin/bash

command -v git >/dev/null 2>&1 || { echo "Install git and try again." >&2; exit 1; }
echo "Installing zsh..." &&
sudo apt-get -y install zsh &&
echo "Installing rbenv..." &&
git clone https://github.com/rbenv/rbenv.git ~/.rbenv &&
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build &&
echo "Installing git-prompt..." &&
git clone https://github.com/olivierverdier/zsh-git-prompt.git ~/zsh-git-prompt &&
cp ./.zshrc ~/.zshrc &&
if [[ x$DISPLAY != x ]]; then
  echo "GUI found. Installing terminator..." &&
  sudo apt-get -y install terminator &&
  mkdir ~/.config/terminator &&
  cp ./config ~/.config/terminator/config
else
  echo "Seems like there is no GUI. Installing Tmux..." &&
  sudo apt-get -y install tmux &&
  cp ./.tmux.conf ~/.tmux.conf &&
  echo "Installing mouse in console for you..." &&
  sudo apt-get -y install gpm
fi
echo "Workspace has been setup. Now change your default shell to zsh."
